### ISSUE TITLE
关于该软件的使用问题

### ISSUE THREAD

**Issue by WSATS25** [laoxinH/crosscore-mod-manager#1]
我下载并使用了大佬您的软件，并且在正确使用了shizuku的情况下发现软件识别不了zip压缩包，并且自己重新按照你提供的文件模板自己打包压缩了zip压缩包也识别不了
  我在反复试验的情况下发现：如果我将zip压缩包放在配置mod目录里，之后启动软件，软件似乎会将zip删除。我尝试放在手机下载目录或qq下载目录软件也无法识别。
  我现在怀疑两种情况：一，是我使用的手机：荣耀70本身有问题；二，是您的软件有bug
  祝您生活愉快

**Comment by laoxinH** [comment]
可以联系我QQ1966843839

**Comment by laoxinH** [comment]
> 我下载并使用了大佬你的软件，并且在正确使用了shizuku的情况下发现软件识别不了zip压缩包，并且自己重新按照你提供的文件模板自己压缩了zip压缩包也识别不了 我试验的情况发现：如果我将zip压缩包放在配置mod目录里，启动软件后，软件好像把zip删除了。我尝试放在手机下载目录或qq下载目录软件也无法识别。 我现在怀疑两个种情况：一，是我使用的手机：荣耀70本身有问题；二，是您的软件有bug 祝您生活愉快

我尝试复现你所说的问题，并没有成功，你可以联系我qq 1966843839

**Comment by Alex-Mercer-1** [comment]
> 可以联系我QQ1966843839

大佬，我也出现了这个问题

**Comment by laoxinH** [comment]
> 我下载并使用了大佬您的软件，并且在正确使用了shizuku的情况下发现软件识别不了zip压缩包，并且自己重新按照你提供的文件模板自己打包压缩了zip压缩包也识别不了 我在反复试验的情况下发现：如果我将zip压缩包放在配置mod目录里，之后启动软件，软件似乎会将zip删除。我尝试放在手机下载目录或qq下载目录软件也无法识别。 我现在怀疑两种情况：一，是我使用的手机：荣耀70本身有问题；二，是您的软件有bug 祝您生活愉快

bug已修复，感谢反馈
