### ISSUE TITLE
要求新增自定義遊戲路徑

### ISSUE THREAD

**Issue by kenwho** [laoxinH/crosscore-mod-manager#14]
你好 最近一週交錯戰線的國際服開了 現行關於此遊戲只支援國服/B服 請問可以加一個自定義遊戲路徑的選項嗎 謝謝

**Comment by laoxinH** [comment]
国际服的包名可以给一个嘛

**Comment by laoxinH** [comment]
> 你好 最近一週交錯戰線的國際服開了 現行關於此遊戲只支援國服/B服 請問可以加一個自定義遊戲路徑的選項嗎 謝謝

已添加国际服配置，有需要自行下载，自定义游戏看仓库主页的文档

**Comment by kenwho** [comment]
謝謝你
