### ISSUE TITLE
使用后的一些想法

### ISSUE THREAD

**Issue by ty201115** [laoxinH/crosscore-mod-manager#18]
1、这个开启mod的方式好像是直接复制过去，我在关闭mod后，游戏里仍然是mod开启状态，能否先把原文件改名，再复制mod文件，这样关闭mod时可以回到开启mod之前的样子。如果只是直接复制那关闭有什么用。
2、能否在多个mod涉及相同文件时，提示并且可以选择顺序
3、能否添加mod分组的功能

**Comment by laoxinH** [comment]
> 1、这个开启mod的方式好像是直接复制过去，我在关闭mod后，游戏里仍然是mod开启状态，能否先把原文件改名，再复制mod文件，这样关闭mod时可以回到开启mod之前的样子。如果只是直接复制那关闭有什么用。 2、能否在多个mod涉及相同文件时，提示并且可以选择顺序 3、能否添加mod分组的功能

配置文件问题已修复重新下载配置文件即可

**Comment by laoxinH** [comment]
> 1、这个开启mod的方式好像是直接复制过去，我在关闭mod后，游戏里仍然是mod开启状态，能否先把原文件改名，再复制mod文件，这样关闭mod时可以回到开启mod之前的样子。如果只是直接复制那关闭有什么用。 2、能否在多个mod涉及相同文件时，提示并且可以选择顺序 3、能否添加mod分组的功能

目前已经添加分组功能，相同mod提示暂时不会考虑主要这类mod不存在冲突的情况
